name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: preprod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print GitHub Variables
        run: |
          echo "Checking GitHub Variables..."
          echo "EC2_PUBLIC_IP: '${{ vars.EC2_PUBLIC_IP }}'"

      - name: Deploy to EC2
        run: |
          # Create SSH key file
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

          # SSH into EC2 and deploy
          ssh -i id_rsa -o StrictHostKeyChecking=no ec2-user@${{ vars.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/projectjs
            git fetch origin
            git reset --hard origin/main
            npm install --production
            pm2 restart camelcase-preprod
          EOF
